/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rulls - BigBoss
 */
public class jeuxppc extends javax.swing.JFrame {

    /**
     * Creates new form jeuxppc
     */
    public jeuxppc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pierre = new javax.swing.JButton();
        feuille = new javax.swing.JButton();
        ciseau = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblJeux = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        lblScoreUser = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        lblScorePC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piedra.png"))); // NOI18N
        pierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pierreActionPerformed(evt);
            }
        });

        feuille.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        feuille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feuilleActionPerformed(evt);
            }
        });

        ciseau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tijera.png"))); // NOI18N
        ciseau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciseauActionPerformed(evt);
            }
        });

        lblMessage.setText("Buena Suerte Amigos");

        lblJeux.setText("Jeu de Pierre, Feuille et Ciseaux");

        lblInfo.setText("Pierre, Feuille et Ciseau");

        score1.setText("Score Utilisateur:");

        lblScoreUser.setText("0");

        score2.setText("Score Ordinateur:");

        lblScorePC.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pierre)
                            .addGap(18, 18, 18)
                            .addComponent(feuille)
                            .addGap(18, 18, 18)
                            .addComponent(ciseau))
                        .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(score1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblScoreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(score2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblScorePC)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblJeux)
                .addGap(12, 12, 12)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ciseau)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(feuille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(score1)
                    .addComponent(lblScoreUser)
                    .addComponent(score2)
                    .addComponent(lblScorePC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pierreActionPerformed
    //********** Selection PC - function MATH 
        int randomNumber = (int) Math.round(Math.random() * 2)+1;
        
    //********** Gagnant vs Pierre
            switch (randomNumber) {
            case 1:
                lblInfo.setText("Vous avez joué: Pierre et l'ordinateur a joué:Pierre");
                lblResult.setText("Partie Nulle...");
                break;
            case 2:
                lblInfo.setText("Vous avez joué: Pierre et l'ordinateur a joué:Feuille");
                lblResult.setText("Vous avez Perdu!, La feuille enveloppe la pierre et gagne. ");
                break;
            case 3:
                lblInfo.setText("Vous avez joué: Pierre et l'ordinateur a joué:Ciseau");
                lblResult.setText("Vous avez Gagne!!!, La pierre écrase les ciseaux et gagne. ");
                break;
        }
        
        
    }//GEN-LAST:event_pierreActionPerformed

    private void feuilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feuilleActionPerformed
     //********** Selection PC - function MATH 
        int randomNumber = (int) Math.round(Math.random() * 2)+1;
        
    //********** Gagnant vs Feuille
            switch (randomNumber) {
            case 1:
                lblInfo.setText("Vous avez joué: Feuille et l'ordinateur a joué:Pierre");  
                lblResult.setText("Vous avez Gagne!!!La feuille enveloppe la pierre et gagne. ");
                break;
            case 2:
                lblInfo.setText("Vous avez joué: Feuille et l'ordinateur a joué:Feuille");
                lblResult.setText("Partie Nulle...");
                break;
            case 3:
                lblInfo.setText("Vous avez joué: Feuille et l'ordinateur a joué:Ciseaux");
                lblResult.setText("Vous avez Perdu!, Les ciseaux découpent la feuille et gagnent.");
                break;
        }     
    }//GEN-LAST:event_feuilleActionPerformed

    private void ciseauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciseauActionPerformed
     //********** Selection PC - function MATH 
        int randomNumber = (int) Math.round(Math.random() * 2)+1;
        
    //********** Gagnant vs Ciseaux
            switch (randomNumber) {
            case 1:
                lblInfo.setText("Vous avez joué: Ciseaux et l'ordinateur a joué:Pierre");  
                lblResult.setText("Vous avez Perdu!La pierre écrase les ciseaux et gagne.. ");
                break;
            case 2:
                lblInfo.setText("Vous avez joué: Ciseaux et l'ordinateur a joué:Feuille");
                lblResult.setText("Vous avez Gagne!!!, Les ciseaux découpent la feuille et gagnent.");
                break;
            case 3:
                lblInfo.setText("Vous avez joué: Ciseaux et l'ordinateur a joué:Ciseaux");
                lblResult.setText("Partie Nulle...");
                break;
        }  
    }//GEN-LAST:event_ciseauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jeuxppc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jeuxppc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jeuxppc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jeuxppc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jeuxppc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ciseau;
    private javax.swing.JButton feuille;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblJeux;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblScorePC;
    private javax.swing.JLabel lblScoreUser;
    private javax.swing.JButton pierre;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    // End of variables declaration//GEN-END:variables
}
